[__config__]
oldver = ".nvchecker/oldver.json"
newver = ".nvchecker/newver.json"

[deepin-wine10-stable]
source = "cmd"
cmd = "python tools/deepin_wine10_stable/check.py"

[spark-store-console-bin]
source = "regex"
url = "https://gitee.com/api/v5/repos/spark-store-project/spark-store/releases?page=1&per_page=100&direction=desc"
regex = '''"name"\s*:\s*"spark-store-console_([^"/]+)_all\.deb"'''
include_regex = '''[0-9].*-console[0-9]+(?:\.[0-9]+)?'''
sort_version_key = "parse_version"
encoding = "utf-8"

[serenity-bin]
source = "github"
github = "SagerNet/serenity"
use_latest_release = true
prefix = "v"

[hfd-git]
source = "git"
git = "https://gist.github.com/padeoe/697678ab8e528b85a2a7bddafea1fa4f.git"
use_commit = true
